export const types = Object.freeze({
  // Sync
  MOVIES_START_FETCHING: "MOVIES_START_FETCHING",
  MOVIES_STOP_FETCHING: "MOVIES_STOP_FETCHING",
  MOVIES_SET_FETCHING_ERROR: "MOVIES_SET_FETCHING_ERROR",
  MOVIES_FILL: "MOVIES_FILL",

  // Async
  MOVIES_FETCH_ASYNC: "MOVIES_FETCH_ASYNC"
});
